# run: conda env create --file environment.yml
name: autodetect
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - numpy=1.19.2
  - pytorch=1.7.1
  - scikit-learn=0.23.2
  - scipy=1.6.0
