name: Build docs

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    name: "Build and deploy documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: "actions/setup-python@v4"
        with:
            python-version: 3.11
            cache: 'pip'
      - run: pip install .[docs]
      - name: Build documentation
        run: cd docs && make html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
